repos:
  - repo: https://github.com/cisagov/pre-commit-packer
    rev: v0.0.2
    hooks:
      - id: packer_validate
        args:
          - manual_file_entry
      - id: packer_fmt
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v2.3.0
  #   hooks:
  #   -   id: check-yaml
  #   -   id: end-of-file-fixer
  #   -   id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
