trigger:
  batch: "true"

name: $(BuildID)

variables:
  - group: keyvault-image-build-variables
  - group: packer-image-build-variables

stages:
- stage: win11_22h2_ent
  displayName: Windows 11 22h2 Enterprise
  jobs:
  - job: build
    displayName: Build Image
    pool:
      vmImage: windows-2019
    steps:
    - task: riezebosch.Packer.PackerTool.PackerTool@0
      displayName: "Use Packer 1.5.6"
      inputs:
        version: "1.5.6"
- task: PackerBuild@1
  inputs:
    templateType: 'custom'
    customTemplateLocation: 'packer-ubuntu-2204.json'
    customTemplateParameters: '{ "ADOServicePrincipalAppId":"$(ADOAppID)", "ADOServicePrincipalSecret":"$(ADOAppSecret)", "ImageDestRG":"$(ImageDestRG)", "ImageOffer":"$(ImageOffer)", "ImagePublisher":"$(ImagePublisher)", "ImageSku":"$(ImageSku)", "Location":"$(Location)", "StorageAccountInstallersKey":"$(StorageAccountKey)", "StorageAccountInstallersName":"$(StorageAccountName)", "StorageAccountInstallersPath":"$(StorageAccountInstallersPath)", "Subnet":"$(Subnet)", "SubscriptionId":"$(SubscriptionId)", "TempResourceGroup":"$(TempResourceGroup)", "TenantId":"$(TenantId)", "VMSize":"$(VMSize)", "VirtualNetwork":"$(VirtualNetwork)", "VirtualNetworkRG":"$(VirtualNetworkRG)"}'
    packerVersion: '1.5.6'
    imageUri: 'BuildImage'
    - task: "nkdagility.variablehydration.variabledehydration-task.variabledehydration@0"
      displayName: 'Save Build Variables: BuildImage'
      inputs:
        prefixes: BuildImage
    - task: PublishBuildArtifacts@1
      displayName: "Publish Artifact: Build Image and associated Template"
      inputs:
        ArtifactName: "Build Image"
