trigger:
  batch: "true"

name: $(BuildID)

variables:
  - group: keyvault-image-build-variables
  - group: packer-image-build-variables

stages:
- stage: win11_22h2_ent
  displayName: Windows 11 22h2 Enterprise
  jobs:
  - job: build
    displayName: Build Image
    pool:
      vmImage: windows-2019
    steps:
    - task: riezebosch.Packer.PackerTool.PackerTool@0
      displayName: "Use Packer 1.9.4"
      inputs:
        version: "1.9.4"
    - task: Packer@1
      inputs:
        connectedServiceType: 'azure'
        azureSubscription: 'azure-hypera'
        command: 'build'
        force: true
        variables-file: 'packer-ubuntu-2204-var.json'
        options: '-only=packer-ubuntu-2204.json'