# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: PackerTool@0
  inputs:
    version: '1.9.4'
    
- script: build ubuntu 22.04 image for azure!
  displayName: 'packer build -var-file=ubuntu-n590590-var.json ubuntu-n590590.json'

