# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

name: $(BuildID)

variables:
  - group: keyvault-image-build-variables
  - group: packer-image-build-variables

stages:
- stage: ubuntu_2204
  displayName: Ubuntu 22.04
  jobs:
  - job: build
    displayName: Build ubuntu 22.04 Golden Image

    pool:
      vmImage: ubuntu-latest

    steps:
    - task: PackerTool@0
      inputs:
        version: '1.9.4'
    - task: Packer@1
      inputs:
        connectedServiceType: 'azure'
        azureSubscription: 'azure-hypera'
        templatePath: 'ubuntu-n590590.json'
        command: 'validate'
        variables-file: 'ubuntu-n590590-var.json'
    - task: Packer@1
      inputs:
        connectedServiceType: 'azure'
        azureSubscription: 'azure-hypera'
        templatePath: 'ubuntu-n590590.json'
        command: 'init'
    - task: Packer@1
      inputs:
        connectedServiceType: 'azure'
        azureSubscription: 'azure-hypera'
        templatePath: 'ubuntu-n590590.json'
        command: 'build'
        variables-file: 'ubuntu-n590590-var.json'
    - script: build ubuntu 22.04 image for azure!
      displayName: 'packer build -var-file=ubuntu-n590590-var.json ubuntu-n590590.json'

