trigger:
  batch: "true"

name: $(BuildID)

variables:
  - group: keyvault-image-build-variables
  - group: packer-image-build-variables

stages:
- stage: win11_22h2_ent
  displayName: Windows 11 22h2 Enterprise
  jobs:
  - job: build
    displayName: Build Image
    pool:
      vmImage: windows-2019
    steps:
    - task: riezebosch.Packer.PackerTool.PackerTool@0
      displayName: "Use Packer 1.5.6"
      inputs:
        version: "1.5.6"
    - task: PackerTool@0
      inputs:
        version: '1.9.4'
    - task: CmdLine@2
      inputs:
        script: |
          echo "Packer version"
          
          packer version